### ISSUE TITLE
Generate Record ID when None exists

### ISSUE THREAD

**Issue by LRSutton** [Senzing/stream-loader#126]
**Describe the bug**
https://github.com/Senzing/stream-loader/blob/68f00a8b6cf36ce66c5c00017cef2533c4a2850d/stream-loader.py#L1438

**Comment by docktermj** [comment]
The code at https://github.com/Senzing/stream-loader/blob/68f00a8b6cf36ce66c5c00017cef2533c4a2850d/stream-loader.py#L1438-L1446 needs to detect if `record_id is None` and if so call `addRecordWithReturnedRecordID()`.

References:
 - https://github.com/Senzing/senzing-sdk-api-specification/blob/master/notebooks/senzing-sdk-api-specification/python/senzing-G2Engine-sdk-api-specification.ipynb

**Comment by docktermj** [comment]
This may be fixed by https://github.com/Senzing/stream-loader/issues/127

Before:
https://github.com/Senzing/stream-loader/blob/68f00a8b6cf36ce66c5c00017cef2533c4a2850d/stream-loader.py#L1438

After:
https://github.com/Senzing/stream-loader/blob/9b47f0cfb091635aba3d9976061bc50ed5bdd6b2/stream-loader.py#L1216-L1218

This avoids "stringifying" the `None` value.

**Comment by docktermj** [comment]
@LRSutton It seems that the changes to #27 did fix the issue.   If OK with you, I'll close this issue.    (If I don't hear back in 7 days, I'll close the issue.)

**Comment by LRSutton** [comment]
Thanks Michael, Go for it!

- Lorin

**Comment by docktermj** [comment]
Thanks!  Closing.
