### ISSUE TITLE
Support existing RabbitMQ queues

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#87]
**Is your feature request related to a problem? Please describe.**
Currently `stream-loader.py` creates its own queue.  It's not flexible when it comes to using queues configured externally.  Things like RabbitMQ "exchanges" are not supported.

**Describe the solution you'd like**
Allow `stream-loader.py` to use queues not created by `stream-loader.py`.  Perhaps a command line option (e.g. `--auto-create-queue`) gives `stream-loader.py` permission to create a queue, if it doesn't exist.

**Comment by jeffadair** [comment]
Queues and exchanges. They both can cause problem if not 'declared' with the expected settings.

I see we have two options on how to handle this
1) Unless instructed, don't declare the exchange and queue and just write to the exchange and queue the user specifies through env vars.
2) expose all the parameters for queues and exchanges as env variables.

#1 is simpler for us, but doesn't do any checked on the queue and requires another container/process/something to create the queue(s) and exchanges.
#2 requires more plumbing but would enable them user to how they wanted they want their queue/exchange to function without anything else. It would also verify the exchange/queue is the expected type/was created as expected. A bit more robust error checking.

I'm leaning a bit more towards #1 since it is less work, and the stream loader/data generator should be light and thin. I don't like needing 'yet another thing', but that seems to be the docker way. Why have a few containers when you have have a bunch. ;)

**Comment by jeffadair** [comment]
The current solution is to add "SENZING_RABBITMQ_USE_EXISTNG_ENTITIES". When that is true stream-loader will attempt to connect (passive declare) to an existing queue with the specified name. It will fail if the queue does not exist. If this is false, it will do an active declare which create the queue if it does not exist, or if it exists, attempt to attach to it and check that queue parameters match.

Stream-loader does not deal with exchanges at all since they are only concerned with routing of messages to queues. To consume a message from a queue the consumer doesn't need to know how it got there. Thus handling the exchange is delegated to the user, or stream-producer.
